// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tickets.Data;

#nullable disable

namespace tickets.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260625023031_AddReviews")]
    partial class AddReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("tickets.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("tickets.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("tickets.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.Property<int>("SeatsPerRow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cinema City",
                            Rows = 5,
                            SeatsPerRow = 8
                        },
                        new
                        {
                            Id = 2,
                            Name = "Helios",
                            Rows = 6,
                            SeatsPerRow = 10
                        },
                        new
                        {
                            Id = 3,
                            Name = "Multikino",
                            Rows = 7,
                            SeatsPerRow = 12
                        });
                });

            modelBuilder.Entity("tickets.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("SeatId");

                    b.HasIndex("ScreeningId", "SeatId")
                        .IsUnique();

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("tickets.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilmTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("FilmTitle", "AppUserId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("tickets.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("FilmTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Screenings");
                });

            modelBuilder.Entity("tickets.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            RowNumber = 1,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            RowNumber = 1,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 1,
                            RowNumber = 1,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            CinemaId = 1,
                            RowNumber = 1,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            CinemaId = 1,
                            RowNumber = 1,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            CinemaId = 1,
                            RowNumber = 1,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            CinemaId = 1,
                            RowNumber = 1,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 8,
                            CinemaId = 1,
                            RowNumber = 1,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 9,
                            CinemaId = 1,
                            RowNumber = 2,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 10,
                            CinemaId = 1,
                            RowNumber = 2,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 11,
                            CinemaId = 1,
                            RowNumber = 2,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 12,
                            CinemaId = 1,
                            RowNumber = 2,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 13,
                            CinemaId = 1,
                            RowNumber = 2,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 14,
                            CinemaId = 1,
                            RowNumber = 2,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 15,
                            CinemaId = 1,
                            RowNumber = 2,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 16,
                            CinemaId = 1,
                            RowNumber = 2,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 17,
                            CinemaId = 1,
                            RowNumber = 3,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 18,
                            CinemaId = 1,
                            RowNumber = 3,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 19,
                            CinemaId = 1,
                            RowNumber = 3,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 20,
                            CinemaId = 1,
                            RowNumber = 3,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 21,
                            CinemaId = 1,
                            RowNumber = 3,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 22,
                            CinemaId = 1,
                            RowNumber = 3,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 23,
                            CinemaId = 1,
                            RowNumber = 3,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 24,
                            CinemaId = 1,
                            RowNumber = 3,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 25,
                            CinemaId = 1,
                            RowNumber = 4,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 26,
                            CinemaId = 1,
                            RowNumber = 4,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 27,
                            CinemaId = 1,
                            RowNumber = 4,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 28,
                            CinemaId = 1,
                            RowNumber = 4,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 29,
                            CinemaId = 1,
                            RowNumber = 4,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 30,
                            CinemaId = 1,
                            RowNumber = 4,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 31,
                            CinemaId = 1,
                            RowNumber = 4,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 32,
                            CinemaId = 1,
                            RowNumber = 4,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 33,
                            CinemaId = 1,
                            RowNumber = 5,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 34,
                            CinemaId = 1,
                            RowNumber = 5,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 35,
                            CinemaId = 1,
                            RowNumber = 5,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 36,
                            CinemaId = 1,
                            RowNumber = 5,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 37,
                            CinemaId = 1,
                            RowNumber = 5,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 38,
                            CinemaId = 1,
                            RowNumber = 5,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 39,
                            CinemaId = 1,
                            RowNumber = 5,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 40,
                            CinemaId = 1,
                            RowNumber = 5,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 41,
                            CinemaId = 2,
                            RowNumber = 1,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 42,
                            CinemaId = 2,
                            RowNumber = 1,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 43,
                            CinemaId = 2,
                            RowNumber = 1,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 44,
                            CinemaId = 2,
                            RowNumber = 1,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 45,
                            CinemaId = 2,
                            RowNumber = 1,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 46,
                            CinemaId = 2,
                            RowNumber = 1,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 47,
                            CinemaId = 2,
                            RowNumber = 1,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 48,
                            CinemaId = 2,
                            RowNumber = 1,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 49,
                            CinemaId = 2,
                            RowNumber = 1,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 50,
                            CinemaId = 2,
                            RowNumber = 1,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 51,
                            CinemaId = 2,
                            RowNumber = 2,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 52,
                            CinemaId = 2,
                            RowNumber = 2,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 53,
                            CinemaId = 2,
                            RowNumber = 2,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 54,
                            CinemaId = 2,
                            RowNumber = 2,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 55,
                            CinemaId = 2,
                            RowNumber = 2,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 56,
                            CinemaId = 2,
                            RowNumber = 2,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 57,
                            CinemaId = 2,
                            RowNumber = 2,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 58,
                            CinemaId = 2,
                            RowNumber = 2,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 59,
                            CinemaId = 2,
                            RowNumber = 2,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 60,
                            CinemaId = 2,
                            RowNumber = 2,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 61,
                            CinemaId = 2,
                            RowNumber = 3,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 62,
                            CinemaId = 2,
                            RowNumber = 3,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 63,
                            CinemaId = 2,
                            RowNumber = 3,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 64,
                            CinemaId = 2,
                            RowNumber = 3,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 65,
                            CinemaId = 2,
                            RowNumber = 3,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 66,
                            CinemaId = 2,
                            RowNumber = 3,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 67,
                            CinemaId = 2,
                            RowNumber = 3,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 68,
                            CinemaId = 2,
                            RowNumber = 3,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 69,
                            CinemaId = 2,
                            RowNumber = 3,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 70,
                            CinemaId = 2,
                            RowNumber = 3,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 71,
                            CinemaId = 2,
                            RowNumber = 4,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 72,
                            CinemaId = 2,
                            RowNumber = 4,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 73,
                            CinemaId = 2,
                            RowNumber = 4,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 74,
                            CinemaId = 2,
                            RowNumber = 4,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 75,
                            CinemaId = 2,
                            RowNumber = 4,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 76,
                            CinemaId = 2,
                            RowNumber = 4,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 77,
                            CinemaId = 2,
                            RowNumber = 4,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 78,
                            CinemaId = 2,
                            RowNumber = 4,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 79,
                            CinemaId = 2,
                            RowNumber = 4,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 80,
                            CinemaId = 2,
                            RowNumber = 4,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 81,
                            CinemaId = 2,
                            RowNumber = 5,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 82,
                            CinemaId = 2,
                            RowNumber = 5,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 83,
                            CinemaId = 2,
                            RowNumber = 5,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 84,
                            CinemaId = 2,
                            RowNumber = 5,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 85,
                            CinemaId = 2,
                            RowNumber = 5,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 86,
                            CinemaId = 2,
                            RowNumber = 5,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 87,
                            CinemaId = 2,
                            RowNumber = 5,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 88,
                            CinemaId = 2,
                            RowNumber = 5,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 89,
                            CinemaId = 2,
                            RowNumber = 5,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 90,
                            CinemaId = 2,
                            RowNumber = 5,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 91,
                            CinemaId = 2,
                            RowNumber = 6,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 92,
                            CinemaId = 2,
                            RowNumber = 6,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 93,
                            CinemaId = 2,
                            RowNumber = 6,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 94,
                            CinemaId = 2,
                            RowNumber = 6,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 95,
                            CinemaId = 2,
                            RowNumber = 6,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 96,
                            CinemaId = 2,
                            RowNumber = 6,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 97,
                            CinemaId = 2,
                            RowNumber = 6,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 98,
                            CinemaId = 2,
                            RowNumber = 6,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 99,
                            CinemaId = 2,
                            RowNumber = 6,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 100,
                            CinemaId = 2,
                            RowNumber = 6,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 101,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 102,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 103,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 104,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 105,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 106,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 107,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 108,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 109,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 110,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 111,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 112,
                            CinemaId = 3,
                            RowNumber = 1,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 113,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 114,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 115,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 116,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 117,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 118,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 119,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 120,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 121,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 122,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 123,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 124,
                            CinemaId = 3,
                            RowNumber = 2,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 125,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 126,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 127,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 128,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 129,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 130,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 131,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 132,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 133,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 134,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 135,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 136,
                            CinemaId = 3,
                            RowNumber = 3,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 137,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 138,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 139,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 140,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 141,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 142,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 143,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 144,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 145,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 146,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 147,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 148,
                            CinemaId = 3,
                            RowNumber = 4,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 149,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 150,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 151,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 152,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 153,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 154,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 155,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 156,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 157,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 158,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 159,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 160,
                            CinemaId = 3,
                            RowNumber = 5,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 161,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 162,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 163,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 164,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 165,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 166,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 167,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 168,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 169,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 170,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 171,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 172,
                            CinemaId = 3,
                            RowNumber = 6,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 173,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 174,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 175,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 176,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 177,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 178,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 179,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 180,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 181,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 182,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 183,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 184,
                            CinemaId = 3,
                            RowNumber = 7,
                            SeatNumber = 12
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("tickets.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("tickets.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tickets.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("tickets.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tickets.Models.Reservation", b =>
                {
                    b.HasOne("tickets.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tickets.Models.Screening", "Screening")
                        .WithMany("Reservations")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tickets.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Screening");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("tickets.Models.Review", b =>
                {
                    b.HasOne("tickets.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("tickets.Models.Screening", b =>
                {
                    b.HasOne("tickets.Models.Cinema", "Cinema")
                        .WithMany("Screenings")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("tickets.Models.Seat", b =>
                {
                    b.HasOne("tickets.Models.Cinema", "Cinema")
                        .WithMany("Seats")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("tickets.Models.Cinema", b =>
                {
                    b.Navigation("Screenings");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("tickets.Models.Screening", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
